name: Publish to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: npm install
      uses: npm ci
    - name: run the unit tests
      uses: npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push to GitHub Container Registry
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker login --username Nivedithabp --password ${{secrets.ACCESS_TOKEN}} ghcr.io
        docker build -t ghcr.io/nivedithabp/arithmetic-service:1.0 --file Dockerfile .
        docker push ghcr.io/nivedithabp/arithmetic-service:1.0
